services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: sql_MS
    ports:
      - 8348:5432
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 13000:8080